ExamStudent/Models/Teacher.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teacher
    {
        public int TeacherId { get; set; }
        public string TeacherName { get; set; }
        public int BoardTypeID { get; set; }
        public int MediumID { get; set; }
        public int SubjectID { get; set; }
    
        public virtual BoardType BoardType { get; set; }
        public virtual Medium Medium { get; set; }
        public virtual Subject Subject { get; set; }
    }
}

ExamStudent/ViewModels/TeacherViewModels.cs
using ExamStudent.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExamStudent.ViewModels
{
    public class TeacherViewModel
    {
        public int TeacherId { get; set; }
        public string TeacherName { get; set; }

        public int BoardTypeID { get; set; }
        public int MediumID { get; set; }
        public int SubjectID { get; set; }

        public string SubjectName { get; set; }


        public List<BoardType> BoardTypeList { get; set; }
        public List<Medium> MediumList { get; set; }

        public List<Subject> SubjectList { get; set; }
    }

    public class TeacherListing
    {
        public List<Teacher> TeachersList { get; set; }
    }

}

ExamStudent/Controllers/TeacherController.cs
using ExamStudent.Models;
using ExamStudent.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExamStudent.Controllers
{
    public class TeacherController : Controller
    {
        ExamStudentContext context = new ExamStudentContext();

        // GET: Teacher
        public ActionResult Index()
        {
            TeacherListing model = new TeacherListing();

            model.TeachersList = context.Teachers.ToList();

            return View(model);
        }

        public ActionResult create()
        {
            ExamStudentContext context = new ExamStudentContext();

            TeacherViewModel teacherViewModel = new TeacherViewModel();

            var boardTypeList = context.BoardTypes.OrderBy(x => x.BoardTypeID).ToList();
            teacherViewModel.BoardTypeList = boardTypeList;

            var mediumList = context.Mediums.OrderBy(x => x.MediumID).ToList();
            teacherViewModel.MediumList = mediumList;

            var subjectList = context.Subjects.OrderBy(x => x.SubjectID).ToList();
            teacherViewModel.SubjectList = subjectList;

            return View(teacherViewModel);
        }

        //For Cascading DropDown List...
        [HttpPost]
        public ActionResult GetMediums(int BoardTypeId)
        {
            var items = context.Mediums
                          .Where(x => x.BoardTypeID == BoardTypeId)
                          .Select(x => new SelectListItem
                          {
                              Value = x.MediumID.ToString(),
                              Text = x.MediumName
                          })
                          .ToList();
            return Json(items, JsonRequestBehavior.AllowGet);
        }

        //For Cascading DropDown List...
        [HttpPost]
        public ActionResult GetStandard(int MediumId)
        {
            var items = context.Subjects
                          .Where(x => x.MediumID == MediumId)
                          .Select(x => new SelectListItem
                          {
                              Value = x.SubjectID.ToString(),
                              Text = x.SubjectName
                          })
                          .ToList();
            return Json(items, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        public ActionResult create(TeacherViewModel model)
        {
            ExamStudentContext context = new ExamStudentContext();

            Teacher teacher = new Teacher();
            teacher.TeacherName = model.TeacherName;
            teacher.BoardTypeID = model.BoardTypeID;
            teacher.MediumID = model.MediumID;
            teacher.SubjectID = model.SubjectID;
          
            context.Teachers.Add(teacher);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Edit(int id)
        {
            ExamStudentContext context = new ExamStudentContext();

            var getteacher =   context.Teachers.Find(id);

            return View(getteacher);
        }

        public ActionResult Delete(int ID)
        {
            using (var context = new ExamStudentContext())
            {
                Teacher teacher = context.Teachers.Where(x => x.TeacherId == ID).FirstOrDefault();

                context.Teachers.Remove(teacher);
                context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

ExamStudent/Views/Teacher/Edit.cshtml
@model ExamStudent.Models.Teacher

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Teacher</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TeacherId)

        <div class="form-group">
            @Html.LabelFor(model => model.TeacherName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TeacherName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TeacherName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BoardTypeID, "BoardTypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("BoardTypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BoardTypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MediumID, "MediumID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("MediumID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MediumID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubjectID, "SubjectID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("SubjectID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubjectID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ExamStudent/Views/Teacher/Index.cshtml
@model ExamStudent.ViewModels.TeacherListing

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<link rel="stylesheet"type="text/css"href="//cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css"/>
<script src="//cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>

<h2 class="text-dark text-center">Teacher Panel</h2>

<div>

    <a href="@Url.Action("create" , "Teacher")"class="btn btn-primary">Add New Teacher</a>

</div>

<br /><br /><br /><br />

<table class="table"id="ProductsTable">

    <thead>

        <tr>

            <th>Teacher Name</th>
            <th>BoardType Name</th>
            <th>Medium Name</th>
            <th>Subject Name</th>
            <th>Action</th>
        </tr>

    </thead>

    <tbody>

        @if (Model.TeachersList != null && Model.TeachersList.Count > 0)
        {
            foreach (var item in Model.TeachersList)
            {
                  <tr>
                      <td>@item.TeacherName</td>
                      <td>@item.BoardType.BoardTypeName</td>
                      <td>@item.Medium.MediumName</td>
                      <td>@item.Subject.SubjectName</td>
                      <td>

                         @Html.ActionLink("Edit" ,"Edit",  new { id=item.TeacherId })

                      </td>
                  </tr>
            }
        }
        else
        {

        }



    </tbody>


</table>

<br /><br /><br />

<script>

     $('#ProductsTable').DataTable();

</script>

ExamStudent/Views/Teacher/create.cshtml
@model ExamStudent.ViewModels.TeacherViewModel

@using System.Web.Mvc


@{
    ViewBag.Title = "create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
    <br /><br /><br /><br />


<script type="text/javascript">
    $(document).ready(function () {
        $('#BoardTypeID').change(function () {
            //alert($('#BoardTypeName').val());
            $.ajax({
                type: "post",
                url: "/Teacher/GetMediums",
                data: { BoardTypeId: $('#BoardTypeID').val() },
                datatype: "json",
                traditional: true,
                success: function (data) {
                    //debugger;
                    //alert("bind data now");
                    var district = "<select id='MediumID'>";
                    district = district + '<option value="">--Select--</option>';

                    for (var i = 0; i < data.length; i++) {
                        district = district + '<option value=' + data[i].Value + '>' + data[i].Text + '</option>';
                    }
                    district = district + '</select>';
                    $('#MediumID').html(district);
                }
            });
        });

        $('#MediumID').change(function () {

            //alert($('#Mediumname').val());

            $.ajax({
                type: "post",
                url: "/Teacher/GetStandard",
                data: { MediumId: $('#MediumID').val() },
                datatype: "json",
                traditional: true,
                success: function (data) {

                    var district = "<select id='SubjectID'>";
                    district = district + '<option value="">--Select--</option>';

                    for (var i = 0; i < data.length; i++) {
                        district = district + '<option value=' + data[i].Value + '>' + data[i].Text + '</option>';
                    }
                    district = district + '</select>';
                    $('#SubjectID').html(district);
                }
            });
        });
    });
</script>

<h2 class="text-center text-dark"> Teacher Create</h2>

<div class="container">

    <div class="container">

        <form method="post">



            <div class="form-group">

                <label>Teacher Name</label>

                <input name="TeacherName" type="text" class="form-control col-md-5" required />

            </div>

            <div class="form-group">
                <label for="inputName">Board Type</label>

                @Html.DropDownListFor(m => m.BoardTypeID, new SelectList(Model.BoardTypeList, "BoardTypeId", "BoardTypeName"),
                                    new { @class = "form-control col-md-5" })
            </div>

            <div class="form-group">
                <label for="inputName">Medium</label>

                @Html.DropDownListFor(m => m.MediumID, new SelectList(Model.MediumList, "MediumId", "MediumName"),
                                    new { @class = "form-control col-md-5" })
            </div>

            <div class="form-group">
                <label for="inputName">Subject</label>

                @Html.DropDownListFor(m => m.SubjectID, new SelectList(Model.SubjectList, "SubjectID", "SubjectName"),
                                   new { @class = "form-control col-md-5" })

            </div>

            <br />

            <button class="btn btn-danger">
                Save
            </button>

        </form>
    </div>
</div>

<br /><br /><br /><br />