ExamStudent/Models/City.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamStudent.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.Tab_User_Info_Temp = new HashSet<Tab_User_Info_Temp>();
        }
    
        public int CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> StateID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tab_User_Info_Temp> Tab_User_Info_Temp { get; set; }
    }
}

ExamStudent/ViewModels/CityViewModel.cs
using ExamStudent.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExamStudent.ViewModels
{
    public class CityViewModel
    {
        public int CityID { get; set; }
        public string CityName { get; set; }
        public Nullable<int> StateID { get; set; }

        public IEnumerable<SelectListItem> StatesSelectListItems { get; set; }

        public List<State> StatesList { get; set; }
    }

    public class EmpCityViewModel
    {
        public int Emp_CityID { get; set; }
        public string Emp_CityName { get; set; }
        public int EmpStateID { get; set; }

        public IEnumerable<SelectListItem> StatesSelectListItems { get; set; }

        public List<EmpState> EmpStatesList { get; set; }
    }
}

ExamStudent/Controllers/CityController.cs
using ExamStudent.Models;
using ExamStudent.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExamStudent.Controllers
{
    public class CityController : Controller
    {
        ExamStudentContext context = new ExamStudentContext();

        // GET: City
        public ActionResult Index()
        {
            var list = context.Cities.ToList();

            return View(list);

           
        }

        public ActionResult Create()
        {
            ExamStudentContext context = new ExamStudentContext();



            CityViewModel cityViewModel = new CityViewModel();

            cityViewModel.StatesSelectListItems = (from objCat in context.States
                                                        select new SelectListItem()
                                                        {
                                                            Text = objCat.StateName,
                                                            Value = objCat.StateID.ToString(),
                                                            Selected = true
                                                        });
            return View(cityViewModel);         
        }

        [HttpPost]
        public JsonResult Create(CityViewModel model)
        {
            ExamStudentContext context = new ExamStudentContext();
           
                var city = new City();
                city.CityID = model.CityID;
                city.StateID = model.StateID;
                city.CityName = model.CityName;
                context.Cities.Add(city);
                context.SaveChanges();

            return Json(new { Success = true, Message = "Item is Added Successfully." }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Delete(int id)
        {
            var getData = context.Cities.Find(id);

            context.Cities.Remove(getData);

            context.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

ExamStudent/Views/City/Create.cshtml
@model ExamStudent.ViewModels.CityViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2>Add-City</h2>


<script type="text/javascript">

    $(document).ready(function () {

        $("#btnsave").click(function () {

            SaveItem();



        });
    });

   

    function SaveItem() {
        var formData = new FormData;
        formData.append("StateID", $("#StateID").val());
        formData.append("CityName", $("#CityName").val());

        // formData.append("ItrmName", $("#ItrmName").val());
        // formData.append("Description", $("#Description").val());
        //formData.append("ItemPrice", $("#ItemPrice").val());
        //formData.append("ImagePath", $("#ImagePath").get(0).files[0]);

        $.ajax({
            async: true,
            dataType: 'JSON',
            type: 'POST',
            contentType: false,
            processData: false,
            url: '/City/Create',
            data: formData,
            success: function (data) {

                if (data.Success) {

                     alert(data.Message);
                     ResetItem();
                }


            },
            error: function () {
                alert('There are some error add to Itme')
            }
        });
    }

</script>


<div class="container">

    <div class="row">

        <form method="post">

            <div class="form-group">
                State:
                @Html.DropDownListFor(model => model.StateID, new SelectList(Model.StatesSelectListItems, "Value", "Text"), new { @class = "form-control" })
            </div>


            <div class="form-group">
                <label>City Name</label>
                <input class="form-control" name="CityName" type="text" id="CityName" />
            </div>

            <input type="button" name="save" value="Save" class="btn btn-primary" id="btnsave" />

            <a href="@Url.Action("Create" , "City")" class="btn btn-danger">Reload this page</a>

        </form>
      
    </div>

</div>

<br /><br /><br />

ExamStudent/Views/City/Index.cshtml
@model IEnumerable<ExamStudent.Models.City>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<h2 class="text-center text-danger">All City</h2>

<hr />
<p>
    @Html.ActionLink("Create New", "Create", "", new { @class = "btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CityName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.StateID)
        </th>
        <th>Action</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.CityName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.StateID)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.CityID }, new { @class = "btn btn-primary" }) |
            @Html.ActionLink("Details", "Details", new { id=item.CityID }, new { @class = "btn btn-danger" }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.CityID }, new { @class = "btn btn-info" })
        </td>
    </tr>
}

</table>